Repository fsspec/jupyter-fsspec, pull requests merged in 2025-03, with the labels that each got.

#92 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: maintenance

#93 Add file upload from browser file picker and Jupyter file browser.
  docs/index.md
  jupyter_fsspec/__init__.py
  jupyter_fsspec/handlers.py
  jupyter_fsspec/helper.py
  jupyter_fsspec/schemas.py
  jupyter_fsspec/tests/test_api.py
  jupyter_fsspec/tests/test_end.png
  jupyter_fsspec/utils.py
  package.json
  schema/plugin.json
  src/FssFilesysItem.ts
  src/FssTreeItem.ts
  src/fileUploadContextPopup.ts
  src/handler/fileOperations.ts
  src/index.ts
  src/treeContext.ts
  style/base.css
  yarn.lock
Labels: enhancement

#90 Return response object data if response contains error message
  src/handler/handler.ts
  src/index.ts
Labels: bug

#94 Updated exception handling
  jupyter_fsspec/exceptions.py
  jupyter_fsspec/handlers.py
Labels: bug

#84 Generate API Schema
  jupyter_fsspec/api-static.html
  jupyter_fsspec/api_schema.yml
  jupyter_fsspec/file_manager.py
  jupyter_fsspec/handlers.py
  jupyter_fsspec/models.py
  jupyter_fsspec/schemas.py
  jupyter_fsspec/scripts/update_api_schema.py
Labels: documentation

#109 Remove unused patch handler and tests
  jupyter_fsspec/handlers.py
  jupyter_fsspec/tests/test_api.py
Labels: maintenance

#100 Initial working context refactor
  src/FssFilesysContextMenu.ts
  src/FssFilesysItem.ts
  src/FssTreeItem.ts
  src/FssTreeItemContext.ts
Labels: enhancement

#110 Upload refactors
  src/FssTreeItem.ts
  src/FssTreeItemContext.ts
  src/index.ts
Labels: maintenance

#112 Add upload tests for jupyterlab file browser and native file browser
  jupyter_fsspec/handlers.py
  ui-tests/tests/filesystem_interaction.test.ts
Labels: maintenance, testing

#121 Update menu options for clarity
  docs/index.md
  src/FssFilesysContextMenu.ts
  src/FssTreeItemContext.ts
  src/index.ts
  ui-tests/tests/filesystem_interaction.test.ts
Labels: enhancement

#123 Improve fsspec.open Code Snippet for Better Compatibility
  src/FssFilesysContextMenu.ts
  src/FssTreeItemContext.ts
  ui-tests/tests/filesystem_interaction.test.ts
Labels: maintenance

#122 Continue signal refactors.
  jupyter_fsspec/file_manager.py
  jupyter_fsspec/helper.py
  package.json
  src/FssTreeItem.ts
  src/FssTreeItemContext.ts
  src/index.ts
  ui-tests/tests/filesystem_interaction.test.ts
  yarn.lock
Labels: maintenance
