Repository fsspec/jupyter-fsspec, pull requests merged in 2025-04, with the labels that each got.

#124 Enhanced Frontend Logging System
  .gitignore
  CONTRIBUTING.md
  jest.config.js
  schema/plugin.json
  src/FssFilesysContextMenu.ts
  src/FssFilesysItem.ts
  src/FssTreeItem.ts
  src/FssTreeItemContext.ts
  src/__tests__/jupyter_fsspec.spec.ts
  src/__tests__/logger-settings.test.ts
  src/__tests__/logger.test.ts
  src/fileUploadContextPopup.ts
  src/handler/fileOperations.ts
  src/handler/handler.ts
  src/index.ts
  src/logger.ts
  src/loggerSettings.ts
  ui-tests/tests/jupyter_fsspec.spec.ts
Labels: enhancement

#116 Update path logic
  .github/workflows/api-test.yml
  conftest.py
  jupyter_fsspec/client.py
  jupyter_fsspec/file_manager.py
  jupyter_fsspec/handlers.py
  jupyter_fsspec/tests/test_api.py
  jupyter_fsspec/tests/test_client.py
  jupyter_fsspec/tests/unit/test_filesystem_manager.py
  jupyter_fsspec/utils.py
  src/FssFilesysItem.ts
  src/FssTreeItemContext.ts
  src/handler/fileOperations.ts
  src/index.ts
  ui-tests/tests/filesystem_interaction.test.ts
Labels: bug

#130 Update code blocks using kwargs and real paths
  jupyter_fsspec/handlers.py
  src/FssTreeItemContext.ts
  ui-tests/tests/filesystem_interaction.test.ts
Labels: maintenance

#129 Extra code cleanup/signals conversion.
  src/FssFilesysItem.ts
  src/index.ts
Labels: maintenance

#134 Typescript refactors 1
  src/FssTreeItem.ts
  src/FssTreeItemContext.ts
  src/handler/fileOperations.ts
  src/index.ts
  ui-tests/tests/filesystem_interaction.test.ts
Labels: maintenance

#133 Fixes #132, helper broken
  jupyter_fsspec/helper.py
Labels: maintenance

#135 Absolute paths: add server CLI flag and env variable check for helper
  conftest.py
  jupyter_fsspec/__init__.py
  jupyter_fsspec/file_manager.py
  jupyter_fsspec/handlers.py
Labels: bug

#128 Document path handling updates
  docs/index.md
Labels: documentation

#136 Workflow publishes to PyPI, correct name
  .github/workflows/pypi-publish.yml
Labels: maintenance

#137 Add testpypi workflow
  .github/workflows/test-pypi-publish.yml
Labels: maintenance

#139 Fix docs notes and warnings
  docs/Makefile
  docs/conf.py
  docs/index.md
Labels: documentation
