Repository fsspec/jupyter-fsspec, pull requests merged in 2025-08, with the labels that each got.

#156 Update ui tests
  ui-tests/tests/filesystem_interaction.test.ts
Labels: maintenance, testing

#154 fix: resolve code snippet insertion issues and improve consistency
  src/FssFilesysContextMenu.ts
  src/FssTreeItemContext.ts
Labels: bug

#157 Establish TypeScript foundations and improve core widget typing
  package.json
  src/FssTreeItem.ts
  src/index.ts
  src/types.ts
Labels: maintenance
